DROP DATABASE IF EXISTS meal;
CREATE DATABASE meal CHARACTER SET utf8;
USE meal;
-- tables 
DROP TABLE IF EXISTS email;
CREATE TABLE email(
    idEmail INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(100) NOT NULL,
    emailPassword VARCHAR(100) NOT NULL,
    UNIQUE KEY(email)
) ENGINE = INNODB;
DROP TABLE IF EXISTS users;
CREATE TABLE users(
    idUser INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    fullName VARCHAR(100) NULL,
    description VARCHAR(200) NULL,
    UNIQUE KEY(username)
) ENGINE = INNODB;